services:
  online-store-db:
    image: postgres:15.2
    container_name: 
    restart: on-failure
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
      TZ: Europe/Moscow
    ports:
      - "5432:5432"
    
  online-store-api:
    build:
      context: .
      dockerfile: src/Dockerfile
    working_dir: /usr/src/app/src
    container_name: 
    restart: on-failure
    environment:
      POSTGRES_DB: 
      POSTGRES_PASSWORD: 
      POSTGRES_USER: 
      POSTGRES_HOST: online-store-db
    depends_on:
      - online-store-db
    ports:
    - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000