version: '3.3'

services:
  db:
    image: postgres:15.2
    restart: on-failure
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_PASSWORD}
      interval: 30s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"

volumes:
  postgres_data:
